In [3]:
import pandas as pd
import numpy as np

In [4]:
sensus = {'tinggi' : [158,170,183,191,155,163,180,158,178],
          'berat': [64,86,84,80,49,59,67,54,67],
          'jk': ['pria','pria','pria','pria','wanita','wanita','wanita','wanita','wanita',]
          }

sensus_df = pd.DataFrame(sensus)
sensus_df


tinggi  berat      jk
0     158     64    pria
1     170     86    pria
2     183     84    pria
3     191     80    pria
4     155     49  wanita
5     163     59  wanita
6     180     67  wanita
7     158     54  wanita
8     178     67  wanita

In [11]:
X_train = np.array(sensus_df[['tinggi','berat']])
y_train = np.array(sensus_df[['jk']])

In [12]:
"""mengubah string menjadi numerik karna hanya 2,berbeda dengan lebih tpi harus 1 array"""
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
y_train = lb.fit_transform(y_train)
y_train = y_train.flatten()
y_train

array([0, 0, 0, 0, 1, 1, 1, 1, 1])

In [14]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [17]:
tinggi = 155
berat = 70
X_new = np.array([tinggi,berat]).reshape(1,-1)
X_new

array([[155,  70]])

In [18]:
y_new = model.predict(X_new)
y_new

array([1])

In [19]:
lb.inverse_transform(y_new)

array(['wanita'], dtype='<U6')

In [22]:
"""eucludien digunakan untnuk mengukur jarak"""
misterius = np.array([tinggi,berat])


In [23]:
from scipy.spatial.distance import euclidean
data_jarak = [euclidean(misterius,d) for d in X_train]

[6.708203932499369,
 21.93171219946131,
 31.304951684997057,
 37.36308338453881,
 21.0,
 13.601470508735444,
 25.179356624028344,
 16.278820596099706,
 23.194827009486403]

In [26]:
sensus_df['jarak'] = data_jarak
sensus_df.sort_values(['jarak'])

tinggi  berat      jk      jarak
0     158     64    pria   6.708204
5     163     59  wanita  13.601471
7     158     54  wanita  16.278821
4     155     49  wanita  21.000000
1     170     86    pria  21.931712
8     178     67  wanita  23.194827
6     180     67  wanita  25.179357
2     183     84    pria  31.304952
3     191     80    pria  37.363083

In [28]:
x_test = np.array([[168,65],[180,96],[160,52],[169,67]])
y_test = lb.transform(np.array(['pria','pria','wanita','wanita'])).flatten()


In [29]:
y_pred = model.predict(x_test)
y_pred

array([1, 0, 1, 1])

In [30]:
"""akurasi metrik membanding y test dan y pred"""
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test,y_pred)
acc

0.75

In [31]:
"""presisi bener bener menghitung sebagai positif yg memang positif"""
from sklearn.metrics import precision_score
prec = precision_score(y_test,y_pred)
prec

0.6666666666666666

In [33]:
"""recall adalah proporsi dari data pada bener bener positif dan positif oleh model"""
from sklearn.metrics import recall_score
rec = recall_score(y_test,y_pred)
rec

1.0

In [34]:
from sklearn.metrics import f1_score
f1 = f1_score(y_test,y_pred)
f1


0.8

In [36]:
from sklearn.metrics import classification_report
cr = classification_report(y_test,y_pred)
print(f'Class report \n {cr}')


Class report 
               precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           1       0.67      1.00      0.80         2

    accuracy                           0.75         4
   macro avg       0.83      0.75      0.73         4
weighted avg       0.83      0.75      0.73         4



In [ ]:
"""metric digunakan hanya untuk biner clasifeir dan untuk 2 kelas,dianggap positif atau negatif
makanya metric sangat timpang tinih kita hanya memperhatikan kelas 1"""


In [37]:
"""alternatif dari f1,kalau random prediksi,kalau prediksi random ngawur 0 kalo bener salah -1"""
from sklearn.metrics import matthews_corrcoef
matt = matthews_corrcoef(y_test,y_pred)
print(f'matt \n {matt}')


matt 
 0.5773502691896258
