In [2]:
"""Regresi	adalah cara dari supervised learning,selain classification dan regression
Yang Diprediksi	Angka
Tipe Output	Continuous
Model Sebagai	Best Fit Line
score menggunakan RMSE atau R2
LIHAT CATATAN:
https://ilham1012.com/2019/06/11/regresi-vs-klasifikasi-apa-bedanya/
https://tinyurl.com/s46z6p8x"""
import pandas as pd

In [4]:
sensus = {'tinggi' : [158,170,183,191,155,163,180,158,170],
          'jk': ['pria','pria','pria','pria','wanita','wanita','wanita','wanita','wanita',],
          'berat': [64,86,84,80,49,59,67,54,67]}

sensus_df = pd.DataFrame(sensus)
sensus_df

tinggi      jk  berat
0     158    pria     64
1     170    pria     86
2     183    pria     84
3     191    pria     80
4     155  wanita     49
5     163  wanita     59
6     180  wanita     67
7     158  wanita     54
8     170  wanita     67

In [7]:
import numpy as np
X_train = np.array(sensus_df[['tinggi','jk']])
y_train = np.array(sensus_df['berat'])
print(f'X_train \n {X_train}\n')
print(f'y_train \n {y_train}')


X_train 
 [[158 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [170 'wanita']]

y_train 
 [64 86 84 80 49 59 67 54 67]


In [12]:
"""label binrizer Digunakan untuk mengganti label pria dan wanita menjadi 0 dan 1
sedangkan jika lbeih dari 2 menggunakan label encoder dan pandas get dummy.tapi label
encoder data harus ada jarak seperti redah medium tinggi tidak bisa dipakai di seperti merah,biru hijau kalau gitu
gunakan hot dummy atau one hot encoding
Scikitlearn suggests using OneHotEncoder for X matrix i.e.
the features you feed in a model, and to use a LabelBinarizer for the y labels."""
X_train_transpose = np.transpose(X_train)
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
jk_binarized = lb.fit_transform(X_train_transpose[1])
jk_binarized = jk_binarized.flatten()

In [14]:
"""disini karena jenis kelamin di index ke 1 diganti ke binarizer.Transpose
biar menjadi hlook"""
X_train_transpose[1] = jk_binarized
X_train = X_train_transpose.transpose()
X_train

array([[158, 0],
       [170, 0],
       [183, 0],
       [191, 0],
       [155, 1],
       [163, 1],
       [180, 1],
       [158, 1],
       [170, 1]], dtype=object)

In [16]:
"""disini perbedaan,ingar regression mencari data berdasarkan masukan,dan import regression"""
from sklearn.neighbors import KNeighborsRegressor
K = 3
model = KNeighborsRegressor(n_neighbors=K)
model.fit(X_train,y_train)

KNeighborsRegressor(n_neighbors=3)

In [17]:
"""memprediksi masukkan atas suatu data"""
X_new = np.array([[155,1]])
y_pred = model.predict(X_new)
y_pred

array([55.66666667])

In [21]:
"""testing adalah melemparkan sebagaian data,training ada melatih berdasarkan data
awal.Testing melihat bagaimana reaksi atas model"""
X_test = np.array([[168,0],[180,0],[160,1],[169,1]])
y_test = np.array([65,96,52,67])

In [20]:
"""bandingkan dengan y test dan y pred"""
y_pred2 = model.predict(X_test)
y_pred2

array([70.66666667, 79.        , 59.        , 70.66666667])

In [24]:
"""menggunakan Rsquared untuk melihat error pada model"""
from sklearn.metrics import r2_score
r_squared = r2_score(y_test,y_pred2)
print(f'Rsquared: {r_squared}')

Rsquared: 0.6290565226735438


In [25]:
"""rata rata dari error kuadrat dari prediksi,beda dengan absolut adalah pangkat 2
makin kecil mse nya model baik
https://tentangdata.wordpress.com/tag/root-mean-squared-error/
https://www.youtube.com/watch?v=W8adIcfv16M&list=PL2O3HdJI4voHNEv59SdXKRQVRZAFmwN9E&index=9"""

from sklearn.metrics import mean_squared_error
mean_sq = mean_squared_error(y_test,y_pred2)
print(f'RMSE: {mean_sq}')

RMSE: 95.8888888888889


In [28]:
"""rumus ini mengurani jumlah y-yi atau hasil prediksi y tes dan pred
disini nilai error atau selisih prediksi dan tes semakin kecil semakin baik model"""
from sklearn.metrics import mean_absolute_error
mean_abs = mean_absolute_error(y_test,y_pred2)
print(f'MSA: {mean_abs}')

MSe: 8.333333333333336


In [31]:
"""perbedaan satuan menyebabka perbedaan prediksi model,dibawah ini dalam bentuk
milimeter"""
from scipy.spatial.distance import euclidean
X_trainmm = np.array([[1700,0],[1600,1]])
X_new = np.array([[1640,0]])
[euclidean(X_new[0],d) for d in X_trainmm]
#hasil 60 ada perbedaan 1700 - 1640

[60.0, 40.01249804748511]

In [32]:
"""standarized score"""
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()


In [33]:
X_trainmm = np.array([[1700,0],[1600,1]])
X_trainmm_scaled = ss.fit_transform(X_trainmm)
print(f'X_trainmm scaled: {X_trainmm_scaled}')

X_new = np.array([[1640,0]])
X_new_scaled = ss.fit_transform(X_new)
print(f'X_new scaled: {X_new_scaled}')

jarak = [euclidean(X_new_scaled[0],d) for d in X_trainmm_scaled]
print(f'jarak: {jarak}')

X_trainmm scaled: [[ 1. -1.]
 [-1.  1.]]
X_new scaled: [[0. 0.]]
jarak: [1.4142135623730951, 1.4142135623730951]


In [40]:
X_train2 = np.array([[158,0],[170,0],[183,0],
                      [191,0],[155,1],[163,1],[180,1],
                      [158,1],[170,1]])
y_train2 = np.array([64,86,84,80,49,59,67,54,67])
X_test2 = np.array([[168,0],[180,0],[160,1],[169,1]])
y_test2 = np.array([65,96,52,67])

In [41]:
X_train2_scaled = ss.fit_transform(X_train2)
X_test2_scaled = ss.fit_transform(X_test2)
print(f'X_train2_scaled: {X_test2_scaled}')
print(f'X_test2_scaled: {X_test2_scaled}')

X_train2_scaled: [[-0.17557375 -1.        ]
 [ 1.50993422 -1.        ]
 [-1.29924573  1.        ]
 [-0.03511475  1.        ]]
X_test2_scaled: [[-0.17557375 -1.        ]
 [ 1.50993422 -1.        ]
 [-1.29924573  1.        ]
 [-0.03511475  1.        ]]


In [42]:
"""dengan ini kita mendpat skor lebih  baik karena bekurang dir sebelumnya"""
model.fit(X_train2_scaled,y_train2)
y_pred3 = model.predict(X_test2_scaled)
MAE = mean_absolute_error(y_test2,y_pred3)
MSE = mean_squared_error(y_test2,y_pred3)

print(f'MAE: {MAE}')
print(f'MSE: {MSE}')


MAE: 7.583333333333336
MSE: 85.13888888888893
